### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by danielveazey** [korganrivera/Blackmarket#1]
```
$ gcc blackmarket-restocker.c
blackmarket-restocker.c: In function ‘weatherreport’:
blackmarket-restocker.c:1700:9: warning: zero-length gnu_printf format string [-Wformat-zero-length]
         else if(humidity < 60.0){   printf("");             last->humidity = 1; }
         ^
blackmarket-restocker.c:1748:9: warning: zero-length gnu_printf format string [-Wformat-zero-length]
         else if(humidity>=40.0 && humidity < 60.0 && last->humidity != 1){  printf("");             last->humidity = 1; }
         ^
/tmp/cccF8HGI.o: In function `main':
blackmarket-restocker.c:(.text+0x39d9): undefined reference to `getche'
blackmarket-restocker.c:(.text+0x3a0f): undefined reference to `getche'
/tmp/cccF8HGI.o: In function `sinefiller':
blackmarket-restocker.c:(.text+0x63d3): undefined reference to `sin'
blackmarket-restocker.c:(.text+0x643e): undefined reference to `sin'
collect2: error: ld returned 1 exit status
```

**Comment by korganrivera** [comment]
At work, but yeah. Fetch is a Windows function. Can't remember the Linux
equivalent

**Comment by korganrivera** [comment]
Fetch iv mean. Fucking phone. I'll write a Linux version when I get home

**Comment by korganrivera** [comment]
The warnings can be ignored.  
Your compiler can't find sin().  Use -lm in your arguments to your compiler, like this:
gcc -lm [source.c]
getche() is a windows only function.  I've just added a linux alternative in the repo, called 
blackmarket-2015.11.10-linux.c
That should do it :+1:

**Comment by danielveazey** [comment]
```
$ gcc -lm blackmarket-2015.11.10-linux.c 
blackmarket-2015.11.10-linux.c: In function ‘weatherreport’:
blackmarket-2015.11.10-linux.c:1747:9: warning: zero-length gnu_printf format string [-Wformat-zero-length]
         else if(humidity < 60.0){   printf("");             last->humidity = 1; }
         ^
blackmarket-2015.11.10-linux.c:1795:9: warning: zero-length gnu_printf format string [-Wformat-zero-length]
         else if(humidity>=40.0 && humidity < 60.0 && last->humidity != 1){  printf("");             last->humidity = 1; }
         ^
/tmp/cc6pHkt4.o: In function `sinefiller':
blackmarket-2015.11.10-linux.c:(.text+0x650f): undefined reference to `sin'
blackmarket-2015.11.10-linux.c:(.text+0x657a): undefined reference to `sin'
collect2: error: ld returned 1 exit status
```

**Comment by korganrivera** [comment]
That makes no sense. I can't see why it can't find sin(). I'll fix it when
I get home.

**Comment by korganrivera** [comment]
Try putting the -lm at the end.
On Nov 11, 2015 7:07 PM, "Korgan Rivera" korganrivera@gmail.com wrote:

That makes no sense. I can't see why it can't find sin(). I'll fix it when
I get home.

**Comment by danielveazey** [comment]
$ gcc blackmarket-2015.11.10-linux.c -lmblackmarket-2015.11.10-linux.c: In
function ‘weatherreport’:
blackmarket-2015.11.10-linux.c:1747:9: warning: zero-length gnu_printf
format string [-Wformat-zero-length]
         else if(humidity < 60.0){   printf("");             last->humidity
= 1; }
         ^
blackmarket-2015.11.10-linux.c:1795:9: warning: zero-length gnu_printf
format string [-Wformat-zero-length]
         else if(humidity>=40.0 && humidity < 60.0 && last->humidity !=
1){  printf("");             last->humidity = 1; }
